ko_fi: ctkqiang
custom: ["https://qr.alipay.com/fkx19369scgxdrkv8mxso92" , "https://donate.stripe.com/00gg2nefu6TK1LqeUY", "https://www.paypal.com/paypalme/ctkqiang" , "https://github.com/ctkqiang/ctkqiang/blob/main/assets/IMG_9859.JPG?raw=true"]
